---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "coala - Code Analysis Made Easy"
keywords:    "coala, review, analysis, static, bears"
description: "coala provides a common command-line interface for linting and fixing all your code, regardless of the programming languages you use."
source_link: "https://github.com/coala-analyzer/coala/"
favicon:     "https://raw.githubusercontent.com/coala-analyzer/coala-artwork/master/artwork/coala_bear.png"
logo:        "https://rawgit.com/coala/artwork/master/artwork/logo/coala_color.svg"
url:         "https://coala.io/"

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
